### ISSUE TITLE
uploading the files in /etc/initramfs-tools/customised_files

### ISSUE THREAD

**Issue by ThomasPf** [rjl6789/initramfs-tools-pi4#1]
Dear Rob,

I'm currently working on a similar set up using raspbian Buster, but am lacking some background knowledge on how to get it up and running. Mostly having some troubles with recognizing the wlan0 during boot.
Would it be possible to share the files in /etc/initramfs-tools/customised_files (with passwords/ssid's rempved ofcourse)?
If you'e prefer contact over email then send me an email when and if convenient @ thomaspfpi@gmail.com.

Regards,
Thomas

**Comment by rjl6789** [comment]
Hi Thomas, that’s not a problem. I have a horrible feeling I might have wiped the sd card I had this set up on. Let me have a hunt through my little pile of unlabelled cards and see if I can find it! Failing that I’ll try setting it up again and putting some notes together. I’m afraid that it will have to wait till end of next week as works a bit manic in the run up to Christmas! Hope you understand.

Kind Regards 

Rob

**Comment by ThomasPf** [comment]
Hi Rob,
I totally understand! thanks a for the update anyway. Any help is much appreciated. This will be step 1. If i get the wifi running, i'm going to try and set up a 4g modem connection on boot, but thats the next challange. Good luck at work and thanks again for the response!

Regards,
Thomas

**Comment by ThomasPf** [comment]
Thank you so much man! Have a great holiday and a happy new year!

**Comment by rjl6789** [comment]
No worries, still need to put together some decent notes and do some more testing. also I’ve identified a couple of issues myself that I’ll eventually get round to.  Merry Christmas!
